# ----- Main Tasks -----
TASK_GARDEN_ENTRY = "Get into the garden"
TASK_GARDEN_WET = "Get the groundskeeper wet"
TASK_GARDEN_KEYS = "Steal the groundskeeper's keys"
TASK_GARDEN_HAT = "Make the groundskeeper wear his sun hat"
TASK_GARDEN_RAKE = "Rake in the lake"
TASK_GARDEN_PICNIC = "Have a picnic"
TASK_GARDEN_FINAL = "Make the groundskeeper hammer his thumb"

TASK_HIGH_STREET_BROOM = "Break the broom"
TASK_HIGH_STREET_PHONE = "Trap the boy in the phone booth"
TASK_HIGH_STREET_GLASSES = "Make the boy wear the wrong glasses"
TASK_HIGH_STREET_BUY = "Make someone buy back their own stuff"
TASK_HIGH_STREET_TV = "Get on TV"
TASK_HIGH_STREET_SHOPPING = "Go shopping"
TASK_HIGH_STREET_FINAL = "Trap the shopkeeper in the garage"

TASK_BACK_GARDENS_VASE = "Make someone break the fancy vase"
TASK_BACK_GARDENS_BUST = "Help the woman dress up the bust"
TASK_BACK_GARDENS_TEA = "Make the man spit out his tea"
TASK_BACK_GARDENS_RIBBON = "Get dressed up with a ribbon"
TASK_BACK_GARDENS_BAREFOOT = "Make the man go barefoot"
TASK_BACK_GARDENS_WASHING = "Do the washing"
TASK_BACK_GARDENS_FINAL = "Make someone prune the prize rose"

TASK_PUB_ENTRY = "Get into the pub"
TASK_PUB_DARTBOARD = "Break the dartboard"
TASK_PUB_BOAT = "Get the toy boat"
TASK_PUB_BUM = "Make the old man fall on his bum"
TASK_PUB_FLOWER = "Be awarded a flower"
TASK_PUB_PINT = "Steal a pint glass and drop it in the canal"
TASK_PUB_TABLE = "Set the table"
TASK_PUB_FINAL = "Drop a bucket on the burly man's head"

TASK_MODEL_VILLAGE_ENTRY = "Get into the model village"
TASK_MODEL_VILLAGE_BELL = "Steal the beautiful miniature golden bell"
TASK_MODEL_VILLAGE_VICTORY = "...and take it all the way back home"

# ----- Extra Tasks -----
EXTRA_TASK_GROUNDSKEEPER = "Lock the groundskeeper out of the garden"
EXTRA_TASK_CABBAGE = "Cabbage picnic"
EXTRA_TASK_PUDDLE = "Trip the boy in the puddle"
EXTRA_TASK_SCALES = "Make the scales go ding"
EXTRA_TASK_UMBRELLA = "Open an umbrella inside the TV shop"
EXTRA_TASK_BUY = "Make someone from outside the high street buy back their own stuff"
EXTRA_TASK_FLOWERS = "Collect the five flowers"
EXTRA_TASK_GARAGE = "Trap the boy in the garage"
EXTRA_TASK_CATCH = "Catch an object as it's thrown over the fence"
EXTRA_TASK_THROWN = "Get thrown over the fence"
EXTRA_TASK_BUST = "Dress up the bust with things from outside the back gardens"
EXTRA_TASK_GOAL = "Score a goal"
EXTRA_TASK_BOAT = "Sail the toy boat under the bridge"
EXTRA_TASK_RIBBON = "Perform at the pub wearing a ribbon"
EXTRA_TASK_HAT = "Steal the old man's woolen hat"

# ----- Speedrun Tasks -----
SPEEDRUN_TASK_GARDEN = "Complete Garden before noon"
SPEEDRUN_TASK_HIGH_STREET = "Complete High Street before noon"
SPEEDRUN_TASK_BACK_GARDENS = "Complete Back Gardens before noon"
SPEEDRUN_TASK_PUB = "Complete Pub before noon"

# ----- Milestone & Completion -----
MILESTONE_ALL_GARDEN = "All Garden tasks complete"
MILESTONE_ALL_HIGH_STREET = "All High Street tasks complete"
MILESTONE_ALL_BACK_GARDENS = "All Back Gardens tasks complete"
MILESTONE_ALL_PUB = "All Pub tasks complete"
MILESTONE_ALL_EXTRA = "All 'To Do (As Well)' tasks complete"
MILESTONE_ALL_SPEEDRUN = "All speedrun tasks complete"
MILESTONE_ALL_MAIN = "All main task lists complete"
MILESTONE_ALL_TASKS = "All tasks complete"

GOAL_ALL_SPEEDRUN = "All speedrun tasks complete (Golden Bell)"
GOAL_ALL_MAIN = "All main task lists complete (Golden Bell)"
GOAL_ALL_TASKS = "All tasks complete (Golden Bell)"
GOAL_ALL_NON_SPEEDRUN = "All main task lists + 'To Do (As Well)' complete (Golden Bell)"
GOAL_MODEL_VILLAGE_ENTRY = "Get into the Model Village (Golden Bell)"
GOAL_ALL_FINAL_TASKS = "Complete the four final area tasks (Golden Bell)"

COMPLETION = "Complete all goals"

# ----- Prop pickups -----

# Starting Area/Hub
PICKUP_BLUE_RIBBON = "Pick up Ribbon (Blue)"
PICKUP_BOOT_HUB = "Pick up Boot (Hub)"
PICKUP_BOOT_START = "Pick up Boot (Start)"
PICKUP_DRINK_CAN = "Pick up Drink Can"
PICKUP_DUMMY = "Pick up Dummy"
PICKUP_FISHING_BOBBER = "Pick up Fishing Bobber"
PICKUP_PINT_BOTTLE_1 = "Pick up Pint Bottle (Hub)"
PICKUP_TENNIS_BALL = "Pick up Tennis Ball"

# Garden
PICKUP_APPLE_1 = "Pick up Apple 1"
PICKUP_APPLE_2 = "Pick up Apple 2"
PICKUP_CARROT_1 = "Pick up Carrot 1"
PICKUP_CARROT_2 = "Pick up Carrot 2"
PICKUP_CARROT_3 = "Pick up Carrot 3"
PICKUP_CARROT_4 = "Pick up Carrot 4"
PICKUP_CARROT_5 = "Pick up Carrot 5"
PICKUP_CARROT_6 = "Pick up Carrot 6"
PICKUP_CARROT_7 = "Pick up Carrot 7"
PICKUP_CARROT_8 = "Pick up Carrot 8"
PICKUP_CARROT_9 = "Pick up Carrot 9"
PICKUP_CARROT_10 = "Pick up Carrot 10"
PICKUP_GROUNDSKEEPERS_HAT = "Pick up Groundskeeper's Hat"
PICKUP_JAM = "Pick up Jam"
PICKUP_KEYS = "Pick up Keys"
PICKUP_PICNIC_MUG = "Pick up Picnic Mug"
PICKUP_RADIO = "Pick up Radio"
PICKUP_SANDWICH_L = "Pick up Sandwich (Left)"
PICKUP_SANDWICH_R = "Pick up Sandwich (Right)"
PICKUP_STRAW_HAT = "Pick up Straw Hat"
PICKUP_THERMOS = "Pick up Thermos"
PICKUP_TROWEL = "Pick up Trowel"
PICKUP_TULIP = "Pick up Tulip"

# High Street
PICKUP_APPLE_CORE_1 = "Pick up Apple Core 1"
PICKUP_APPLE_CORE_2 = "Pick up Apple Core 2"
PICKUP_BOYS_GLASSES = "Pick up Boy's Glasses"
PICKUP_CHALK = "Pick up Chalk"
PICKUP_CUCUMBER_1 = "Pick up Cucumber 1"
PICKUP_CUCUMBER_2 = "Pick up Cucumber 2"
PICKUP_CUCUMBER_3 = "Pick up Cucumber 3"
PICKUP_DISH_SOAP_BOTTLE = "Pick up Dish Soap Bottle"
PICKUP_DUSTBIN_LID = "Pick up Dustbin Lid"
PICKUP_GARDEN_FORK = "Pick up Garden Fork"
PICKUP_HAIRBRUSH = "Pick up Hairbrush"
PICKUP_HORN_RIMMED_GLASSES = "Pick up Horn-Rimmed Glasses"
PICKUP_LEEK_1 = "Pick up Leek 1"
PICKUP_LEEK_2 = "Pick up Leek 2"
PICKUP_LEEK_3 = "Pick up Leek 3"
PICKUP_LILY_FLOWER = "Pick up Lily Flower"
PICKUP_LOO_PAPER = "Pick up Loo Paper"
PICKUP_ORANGE_1 = "Pick up Orange 1"
PICKUP_ORANGE_2 = "Pick up Orange 2"
PICKUP_ORANGE_3 = "Pick up Orange 3"
PICKUP_PINT_BOTTLE_2 = "Pick up Pint Bottle (High Street 1)"
PICKUP_PINT_BOTTLE_3 = "Pick up Pint Bottle (High Street 2)"
PICKUP_RED_GLASSES = "Pick up Red Glasses"
PICKUP_SHOP_CARROT_1 = "Pick up Shop Carrot 1"
PICKUP_SHOP_CARROT_2 = "Pick up Shop Carrot 2"
PICKUP_SHOP_CARROT_3 = "Pick up Shop Carrot 3"
PICKUP_SHOP_TOMATO_1 = "Pick up Shop Tomato 1"
PICKUP_SHOP_TOMATO_2 = "Pick up Shop Tomato 2"
PICKUP_SHOP_TOMATO_3 = "Pick up Shop Tomato 3"
PICKUP_SPRAY_BOTTLE = "Pick up Spray Bottle"
PICKUP_SUNGLASSES = "Pick up Sunglasses"
PICKUP_STEREOSCOPE = "Pick up Stereoscope"
PICKUP_TINNED_FOOD_BLUE = "Pick up Tinned Food (Blue)"
PICKUP_TINNED_FOOD_ORANGE = "Pick up Tinned Food (Orange)"
PICKUP_TINNED_FOOD_YELLOW = "Pick up Tinned Food (Yellow)"
PICKUP_TOOTHBRUSH = "Pick up Toothbrush"
PICKUP_TOY_CAR = "Pick up Toy Car"
PICKUP_TOY_PLANE = "Pick up Fusilage"
PICKUP_WALKIE_TALKIE_1 = "Pick up Walkie Talkie 1"
PICKUP_WALKIE_TALKIE_2 = "Pick up Walkie Talkie 2"
PICKUP_WEED_TOOL = "Pick up Weed Tool"

# Back Gardens
PICKUP_BADMINTON_RACKET = "Pick up Badminton Racket"
PICKUP_BRA = "Pick up Bra"
PICKUP_BUST_GLASSES = "Pick up Bust Glasses"
PICKUP_BUST_HAT = "Pick up Bust Hat"
PICKUP_BUST_PIPE = "Pick up Bust Pipe"
PICKUP_CRICKET_BALL = "Pick up Cricket Ball"
PICKUP_NEWSPAPER = "Pick up Newspaper"
PICKUP_PAINTBRUSH = "Pick up Paintbrush"
PICKUP_POT_STACK = "Pick up Pot Stack"
PICKUP_RIBBON_RED = "Pick up Ribbon (Red)"
PICKUP_ROSE = "Pick up Rose"
PICKUP_SLIPPER_L = "Pick up Slipper (Left)"
PICKUP_SLIPPER_R = "Pick up Slipper (Right)"
PICKUP_SOAP = "Pick up Soap"
PICKUP_SOCK_1 = "Pick up Sock 1"
PICKUP_SOCK_2 = "Pick up Sock 2"
PICKUP_TEA_CUP = "Pick up Tea Cup"
PICKUP_VASE = "Pick up Vase"
PICKUP_VASE_PIECE_1 = "Pick up Broken Vase Piece 1"
PICKUP_VASE_PIECE_2 = "Pick up Broken Vase Piece 2"

# Pub
PICKUP_CANDLESTICK = "Pick up Candlestick"
PICKUP_CORK = "Pick up Cork"
PICKUP_DART_1 = "Pick up Dart 1"
PICKUP_DART_2 = "Pick up Dart 2"
PICKUP_DART_3 = "Pick up Dart 3"
PICKUP_FLOWER_FOR_VASE = "Pick up Flower for Vase"
PICKUP_FORK_1 = "Pick up Fork 1"
PICKUP_FORK_2 = "Pick up Fork 2"
PICKUP_GREEN_QUOIT_1 = "Pick up Green Quoit 1"
PICKUP_GREEN_QUOIT_2 = "Pick up Green Quoit 2"
PICKUP_GREEN_QUOIT_3 = "Pick up Green Quoit 3"
PICKUP_HARMONICA = "Pick up Harmonica"
PICKUP_KNIFE_1 = "Pick up Knife 1"
PICKUP_KNIFE_2 = "Pick up Knife 2"
PICKUP_LETTER = "Pick up Letter"
PICKUP_OLD_MANS_WOOLEN_HAT = "Pick up Old Man's Woolen Hat"
PICKUP_PEPPER_GRINDER = "Pick up Pepper Grinder"
PICKUP_PINT_GLASS = "Pick up Pint Glass"
PICKUP_PLATE_1 = "Pick up Plate 1"
PICKUP_PLATE_2 = "Pick up Plate 2"
PICKUP_PLATE_3 = "Pick up Plate 3"
PICKUP_PUB_TOMATO_1 = "Pick up Boxed Pub Tomato 1"
PICKUP_PUB_TOMATO_2 = "Pick up Boxed Pub Tomato 2"
PICKUP_PUB_TOMATO_3 = "Pick up Boxed Pub Tomato 3"
PICKUP_PUB_TOMATO_4 = "Pick up Boxed Pub Tomato 4"
PICKUP_PUB_TOMATO_5 = "Pick up Boxed Pub Tomato 5"
PICKUP_PUB_TOMATO_6 = "Pick up Boxed Pub Tomato 6"
PICKUP_PUB_TOMATO_7 = "Pick up Boxed Pub Tomato 7"
PICKUP_PUB_TOMATO_8 = "Pick up Boxed Pub Tomato 8"
PICKUP_PUB_TOMATO_9 = "Pick up Boxed Pub Tomato 9"
PICKUP_PUB_TOMATO_10 = "Pick up Pub Tomato 1"
PICKUP_PUB_TOMATO_11 = "Pick up Pub Tomato 2"
PICKUP_PUB_WOMANS_CLOTH = "Pick up Pub Woman's Cloth"
PICKUP_RED_QUOIT_1 = "Pick up Red Quoit 1"
PICKUP_RED_QUOIT_2 = "Pick up Red Quoit 2"
PICKUP_RED_QUOIT_3 = "Pick up Red Quoit 3"
PICKUP_TOY_BOAT = "Pick up Toy Boat"

# Model Village
PICKUP_MINI_MAIL_PILLAR = "Pick up Mini Mail Pillar"
PICKUP_MINI_GOOSE = "Pick up Mini Goose"
PICKUP_MINI_PERSON = "Pick up Mini Person"
PICKUP_MINI_PERSON_CHILD = "Pick up Mini Person (Child)"
PICKUP_MINI_PERSON_GARDENER = "Pick up Mini Person (Gardener)"
PICKUP_MINI_PERSON_JUMPSUIT = "Pick up Mini Person (Jumpsuit)"
PICKUP_MINI_PERSON_OLD_WOMAN = "Pick up Mini Person (Old Woman)"
PICKUP_MINI_PERSON_POSTIE = "Pick up Mini Person (Postie)"
PICKUP_MINI_PERSON_VEST_MAN = "Pick up Mini Person (Vest Man)"
PICKUP_MINI_PHONE_DOOR = "Pick up Mini Phone Door"
PICKUP_MINI_SHOVEL = "Pick up Mini Shovel"
PICKUP_POPPY_FLOWER = "Pick up Poppy Flower"
PICKUP_TIMBER_HANDLE = "Pick up Timber Handle"

PICKUP_GOLDEN_BELL = "Pick up Golden Bell"

# ----- Prop drags -----

# Starting Area/Hub
DRAG_FENCE_BOLT = "Drag Fence Bolt"
DRAG_TACKLE_BOX = "Drag Tackle Box"

# Garden
DRAG_ESKY = "Drag Esky"
DRAG_GUMBOOT_1 = "Drag Gumboot 1"
DRAG_GUMBOOT_2 = "Drag Gumboot 2"
DRAG_MALLET = "Drag Mallet"
DRAG_NO_GOOSE_SIGN_GARDEN = "Drag No Goose Sign (Garden)"
DRAG_PICNIC_BASKET = "Drag Picnic Basket"
DRAG_PUMKPIN_1 = "Drag Pumpkin 1"
DRAG_PUMKPIN_2 = "Drag Pumpkin 2"
DRAG_PUMKPIN_3 = "Drag Pumpkin 3"
DRAG_PUMKPIN_4 = "Drag Pumpkin 4"
DRAG_RAKE = "Drag Rake"
DRAG_SHOVEL = "Drag Shovel"
DRAG_TOPSOIL_BAG_1 = "Drag Topsoil Bag 1"
DRAG_TOPSOIL_BAG_2 = "Drag Topsoil Bag 2"
DRAG_TOPSOIL_BAG_3 = "Drag Topsoil Bag 3"
DRAG_WATERING_CAN = "Drag Watering Can"
DRAG_WOODEN_CRATE = "Drag Wooden Crate"

# High Street
DRAG_ADDING_MACHINE = "Drag Adding Machine"
DRAG_BABY_DOLL = "Drag Baby Doll"
DRAG_BROKEN_BROOM_HEAD = "Drag Broken Broom Head"
DRAG_DUSTBIN = "Drag Dustbin"
DRAG_PRICING_GUN = "Drag Pricing Gun"
DRAG_PUSH_BROOM = "Drag Push Broom"
DRAG_SHOPPING_BASKET = "Drag Shopping Basket"
DRAG_UMBRELLA_BLACK = "Drag Umbrella (Black)"
DRAG_UMBRELLA_RAINBOW = "Drag Umbrella (Rainbow)"
DRAG_UMBRELLA_RED = "Drag Umbrella (Red)"

# Back Gardens
DRAG_CLIPPERS = "Drag Clippers"
DRAG_CRICKET_BAT = "Drag Cricket Bat"
DRAG_DRAWER = "Drag Drawer"
DRAG_DUCK_STATUE = "Drag Duck Statue"
DRAG_ENAMEL_JUG = "Drag Enamel Jug"
DRAG_FROG_STATUE = "Drag Frog Statue"
DRAG_JEREMY_FISH = "Drag Jeremy Fish"
DRAG_NO_GOOSE_SIGN_CLEAN = "Drag No Goose Sign (Clean)"
DRAG_NO_GOOSE_SIGN_MESSY = "Drag No Goose Sign (Messy)"
DRAG_ROSE_BOX = "Drag Rose Box"
DRAG_TEA_POT = "Drag Tea Pot"

# Pub
DRAG_BUCKET = "Drag Bucket"
DRAG_DARTBOARD = "Drag Dartboard"
DRAG_DELIVERY_BOX = "Drag Delivery Box"
DRAG_MOP = "Drag Mop"
DRAG_MOP_BUCKET = "Drag Mop Bucket"
DRAG_NO_GOOSE_SIGN_PUB = "Drag No Goose Sign (Pub)"
DRAG_PARCEL = "Drag Parcel"
DRAG_PORTABLE_STOOL = "Drag Portable Stool"
DRAG_STEALTH_BOX = "Drag Stealth Box"
DRAG_TRAFFIC_CONE = "Drag Traffic Cone"

# Model Village
DRAG_MINI_BENCH = "Drag Mini Bench"
DRAG_MINI_BIRDBATH = "Drag Mini Birdbath"
DRAG_MINI_EASEL = "Drag Mini Easel"
DRAG_MINI_PUMP = "Drag Mini Pump"
DRAG_MINI_STREET_BENCH = "Drag Mini Street Bench"
DRAG_MINI_SUN_LOUNGE = "Drag Mini Sun Lounge"

# ----- Interactions & Events -----

# Starting Area/Hub Interactions
INTERACT_BIKE_BELL = "Ring the bike bell"

# Garden Interactions
INTERACT_GARDEN_TAP = "Turn on the tap in the Garden"
INTERACT_SPRINKLER = "Turn on the sprinkler"

# High Street Interactions
INTERACT_BOYS_LACES_L = "Untie Boy's Laces (Left)"
INTERACT_BOYS_LACES_R = "Untie Boy's Laces (Right)"
INTERACT_UMBRELLA_BLACK = "Open Umbrella (Black)"
INTERACT_UMBRELLA_RAINBOW = "Open Umbrella (Rainbow)"
INTERACT_UMBRELLA_RED = "Open Umbrella (Red)"
INTERACT_UNPLUG_RADIO = "Unplug the shop's radio"
INTERACT_FOOTBALL = "Boop the football"

# Back Gardens Interactions
INTERACT_PURPLE_FLOWER = "Spin the purple flower"
INTERACT_RING_BELL = "Ring the bell in the Back Gardens"
INTERACT_SUNFLOWER = "Spin the sunflower"
INTERACT_TOPIARY = "Peck at the topiary"
INTERACT_TRELLIS = "Break through the trellis"
INTERACT_WIND_CHIME_C = "Play Wind Chime (C)"
INTERACT_WIND_CHIME_D = "Play Wind Chime (D)"
INTERACT_WIND_CHIME_E = "Play Wind Chime (E)"
INTERACT_WIND_CHIME_F = "Play Wind Chime (F)"
INTERACT_WIND_CHIME_G = "Play Wind Chime (G)"
INTERACT_WIND_CHIME_A = "Play Wind Chime (A)"
INTERACT_WIND_CHIME_B = "Play Wind Chime (B)"
INTERACT_WINDMILL = "Spin the windmill"

# Pub interactions Interactions
INTERACT_BURLY_MANS_LACES_L = "Untie Burly Man's Laces (Left)"
INTERACT_BURLY_MANS_LACES_R = "Untie Burly Man's Laces (Right)"
INTERACT_PUB_TAP = "Turn on the tap in the Pub"
INTERACT_VAN_DOOR_L = "Close Van Door (Left)"
INTERACT_VAN_DOOR_R = "Close Van Door (Right)"

# Events
BREAK_THROUGH_BOARDS = "Break through the boards to the Back Gardens"
DROP_ITEM_IN_WELL = "Drop something in the well"
LOCK_GROUNDSKEEPER_IN = "Lock the groundskeeper IN the garden"
MAKE_WOMAN_FIX_TOPIARY = "Make the woman fix the topiary"
OPEN_INTRO_GATE = "Open the intro gate"
POSE_AS_DUCK = "Pose as a duck statue"
SHORT_OUT_RADIO = "Short out the garden radio"
TRIP_BURLY_MAN = "Trip the burly man"

# ----- Model Church Pecks -----

PECK_DOORWAY = "Peck Model Church Doorway"
PECK_TOWER = "Peck Model Church Tower"

PECK_DOORWAY_1 = "Peck Model Church Doorway 1"
PECK_DOORWAY_2 = "Peck Model Church Doorway 2"
PECK_DOORWAY_3 = "Peck Model Church Doorway 3"
PECK_DOORWAY_4 = "Peck Model Church Doorway 4"
PECK_DOORWAY_5 = "Peck Model Church Doorway 5"
PECK_DOORWAY_6 = "Peck Model Church Doorway 6"
PECK_DOORWAY_7 = "Peck Model Church Doorway 7"
PECK_DOORWAY_8 = "Peck Model Church Doorway 8"
PECK_DOORWAY_9 = "Peck Model Church Doorway 9"
PECK_DOORWAY_10 = "Peck Model Church Doorway 10"
PECK_DOORWAY_11 = "Peck Model Church Doorway 11"
PECK_DOORWAY_12 = "Peck Model Church Doorway 12"
PECK_DOORWAY_13 = "Peck Model Church Doorway 13"
PECK_DOORWAY_14 = "Peck Model Church Doorway 14"
PECK_DOORWAY_15 = "Peck Model Church Doorway 15"
PECK_DOORWAY_16 = "Peck Model Church Doorway 16"
PECK_DOORWAY_17 = "Peck Model Church Doorway 17"
PECK_DOORWAY_18 = "Peck Model Church Doorway 18"
PECK_DOORWAY_19 = "Peck Model Church Doorway 19"

PECK_TOWER_1 = "Peck Model Church Tower 1"
PECK_TOWER_2 = "Peck Model Church Tower 2"
PECK_TOWER_3 = "Peck Model Church Tower 3"
PECK_TOWER_4 = "Peck Model Church Tower 4"
PECK_TOWER_5 = "Peck Model Church Tower 5"
PECK_TOWER_6 = "Peck Model Church Tower 6"
PECK_TOWER_7 = "Peck Model Church Tower 7"
PECK_TOWER_8 = "Peck Model Church Tower 8"
PECK_TOWER_9 = "Peck Model Church Tower 9"
PECK_TOWER_10 = "Peck Model Church Tower 10"
PECK_TOWER_11 = "Peck Model Church Tower 11"
PECK_TOWER_12 = "Peck Model Church Tower 12"
PECK_TOWER_13 = "Peck Model Church Tower 13"
PECK_TOWER_14 = "Peck Model Church Tower 14"
PECK_TOWER_15 = "Peck Model Church Tower 15"
PECK_TOWER_16 = "Peck Model Church Tower 16"